[package]
name = "atac"
description = "Arguably a Terminal API Client. Feature-full, free, open-source, offline and account-less."
version = "0.14.0"
authors = ["julien-cpsn"]
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://github.com/Julien-cpsn/ATAC/wiki"
homepage = "https://github.com/Julien-cpsn/ATAC"
repository = "https://github.com/Julien-cpsn/ATAC"
keywords = ["API", "TUI", "Postman", "Insomnia"]

exclude = [
    ".github/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.27", default-features = false, features = ["cookies", "rustls-tls-native-roots", "multipart", "gzip", "brotli", "deflate", "stream"] }
reqwest_cookie_store = "0.6.0"
cookie_store = "0.20.0"
ratatui = "0.26.2"
crossterm = "0.27.0"
crokey = "1.0.0"
tui-big-text = "0.4.2"
tui-tree-widget = "0.19.0"
tui-textarea = { version = "0.4.0", features = ["ratatui"] }
throbber-widgets-tui = "0.5.0"
ratatui-image = { version = "1.0.0", features = ["crossterm"] }
image = "0.24.9"
syntect = "5.2.0"
serde = { version = "1.0.197", features = ["derive", "rc"] }
serde_json = "1.0.114"
jsonxf = "1.1.1"
toml = "0.8.11"
deno_core = "0.278.0"
parse_postman_collection = "0.2.3"
clap = { version = "4.5.0", features = ["derive", "color"] }
arboard = "3.3.2"
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros"] }
strum = "0.26.2"
lazy_static = "1.4.0"
nestify = "0.3.3"
snailquote = "0.3.1"
indexmap = { version = "2.2.6", features = ["serde"] }
base64 = "0.22.0"
regex = "1.10.3"
